### ISSUE TITLE
TabuSampler fails for single variable BQMs

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-tabu#27]
To reproduce:
```
>>> import tabu, dimod
>>> tabu.TabuSampler().sample(dimod.BinaryQuadraticModel({'a': 1}, {}, 0, dimod.SPIN))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radomir/work/dwave-tabu/tabu/sampler.py", line 113, in sample
    raise ValueError("'tenure' should be an integer in range [1, num_vars - 1]")
ValueError: 'tenure' should be an integer in range [1, num_vars - 1]
```

**Comment by randomir** [comment]
Fixed with #28.
