### ISSUE TITLE
Error Importing Tabu

### ISSUE THREAD

**Issue by cogrpar** [dwavesystems/dwave-tabu#50]
Hello, I have been trying to import dwave tabu, but I have been experiencing some issues.  When importing the package in python3, I get this result:
``` 
>>>import tabu
Traceback (most recent call last):
  File "/home/chip/.local/lib/python3.5/site-packages/tabu/tabu_search.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /home/chip/.local/lib/python3.5/site-packages/tabu/_tabu_search.so: wrong ELF class: ELFCLASS64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chip/.local/lib/python3.5/site-packages/tabu/__init__.py", line 17, in <module>
    from tabu.tabu_search import TabuSearch
  File "/home/chip/.local/lib/python3.5/site-packages/tabu/tabu_search.py", line 17, in <module>
    _tabu_search = swig_import_helper()
  File "/home/chip/.local/lib/python3.5/site-packages/tabu/tabu_search.py", line 16, in swig_import_helper
    return importlib.import_module('_tabu_search')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_tabu_search' 
```

I suspect that the error has something to do with swig, but I am unsure what to do to resolve it.  Any help would be greatly appreciated.  
Thanks

**Comment by randomir** [comment]
Hi @cogrpar!

This looks like you're using a binary compiled for 64-bit linux, on a 32-bit installation.

Could you provide a bit more context? What's your OS, how did you install the package, are you using venv and how? Thanks.

**Comment by cogrpar** [comment]
Hello @randomir sorry for the trouble, I tried installing this package on another machine and I no longer experience an error.  It was probably just an issue with my other computer.

**Comment by randomir** [comment]
No worries! Let us know if you run into troubles again. Until then, I'm closing this issue. Thanks!
